# Generated by Django 4.1.2 on 2022-10-16 05:20

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=300, null=True)),
                ('title', models.CharField(max_length=500, null=True)),
                ('slug', models.CharField(max_length=200, null=True)),
                ('image', models.ImageField(null=True, upload_to='portal/image', verbose_name='image')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
